<section id="crm">
    <div class="container">
        <div class="content">
            <h2>Comment un outil de Gestion de Projet peut Aider Votre Équipe</h2>
            <p>Suite Logicièle Unique Et Puissante Pour Gérer L'ensemble De Votre Entreprise, Présentée Par Une Entreprise Ayant Une Vision A Long Terme Pour Transformer Votre Façon De Travailler.</p>
            <div class="features">
                <div class="feature">
                    <h2>CRM Security</h2>
                    <p>Cartes Et Réalisez Plus De Ventes Tout En Discutant</p>
                </div>
                <div class="feature">
                    <h2>Marketing Hub</h2>
                    <p>Présentez Vos Produits Dans Des Fiches Produits Élégantes Et Faites</p>
                </div>
            </div>
            <button>Commencer</button>
        </div>
        <div class="background-image">
            <img src="file_assets/Background-end.png" alt="Background image" class="img-fluid bg-image">
        </div>
        <div class="image-content">
            <img src="file_assets/img-section-end.png" alt="End" class="img-fluid">
        </div>
    </div>
</section>

<style>
    #crm {
        position: relative;

        .container {
            display: flex;
            justify-content: space-between;
        }

        .background-image .bg-image {
            position: absolute;
            top: 0;
            left: 60%;
            width: 40%;
            height: 100%;
            z-index: -1;
        }

        .content {
            max-width: 50%;
            padding: 0 50px 0 50px;
            text-align: left;
        }

        .features {
            display: flex;
            justify-content: space-around;
            margin-top: 50px;
        }

        .feature {
            text-align: center;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size:
                16px;
            margin-top: 20px;
        }

        .image-content img {
            max-width: 100%;
            height: auto;
        }
    }
</style>