<section id="footer" class="text-center text-lg-starttext-muted">
    <!-- Section: Social media -->
    <div class="container">
        <section class="socials d-flex justify-content-center justify-content-lg-between p-4">
            <!-- Left -->
            <div class="me-5">
                <a class="footer-brand" href="#">
                    <img src="file_assets/LogoNex.png" alt="Logo" width="35" height="40" class="d-inline-block align-text-top">
                    NexiumiaCRM
                </a>
            </div>
            <div class="icons-social">
                <a target="_blank" href="https://www.instagram.com/tyroliumentertainment/"><i class="ri-instagram-line fs-5 instagram"></i></a>
                <a target="_blank" href="https://www.facebook.com/tyrolium/"><i class="ri-facebook-circle-fill fs-5 facebook"></i></a>
                <a target="_blank" href="https://x.com/TyroliumE"><i class="ri-twitter-fill fs-5 twitter"></i></a>
                <a target="_blank" href="https://www.linkedin.com/company/tyrolium/"><i class="ri-linkedin-box-fill fs-5 linkedin"></i></a>
                <a target="_blank" href="https://www.youtube.com/@Tyrolium"><i class="ri-youtube-fill fs-5 youtube"></i></a>
            </div>
        </section>
        <section class="utils-link d-flex justify-content-center justify-content-lg-between">
            <nav>
                <ul>
<!--                    <li><a href="#">Liens Utiles</a></li>-->
                    <li><a href="index.php#leads-management">Services</a></li>
                    <li><a href="formulaire.php?form=contact">Contacte</a></li>
                    <li><a href="formulaire.php?form=quote">Ce Lancer</a></li>
                </ul>
            </nav>
            <div class="arrow-up">
                <a href="#navbar"><i class="ri-arrow-up-s-line fs-3"></i></a>
            </div>
        </section>
        <section id="links">
            <div class="link1">
                <ul>
                    <li><a href="https://tyrolium.fr/more">Mention Légal</a></li>
                    <li><a href="https://tyrolium.fr/more">CGU</a></li>
                    <li><a href="https://tyrolium.fr/more">CGV</a></li>
                    <li><a target="_blank" href="https://tyrolium.fr">Tyrolium</a></li>
                </ul>
            </div>
            <div class="link2">
                <ul>
                    <li><a href="#leads-management">Solution</a></li>
                    <li><a href="#crm">Produit</a></li>
                    <li><a href="formulaire.php?form=quote">Devis</a></li>
                    <li><a href="formulaire.php?form=login">Se connecter</a></li>
                </ul>
            </div>
            <div class="adress">
                <div class="adress1  border-box mb-2">
                    <p>252 Avenue Jean Jaurès<br>Décines-Charpieu, France</p>
                </div>
                <div class="adress2  border-box">
                    <p><a href="tel:+33611112669">+33 7 56 88 96 97<br>officiel@tyrolium.fr</a></p>
                </div>
            </div>
            <div id="photofooter" class="button-container">
<!--                <img src="file_assets/Photo.png" alt="Image de fond" class="background-image img-fluid">-->
                <button class="launch-button"><a href="formulaire.php?form=quote">Ce Lancer</a></button>
            </div>
        </section>
        <div class="Copyright text-center p-4">
            Copyright ©<a target="_blank" href="https://tyrolium.fr" style="color: white;">Tyrolium</a> | Créer By Maxime Tournier
        </div>
    </div>
</section>
<style>
    #footer {
        background-color: #303030;
        margin-top: 20px;
    }

    #footer .container {
        width: 100%;
        padding: 40px 115px 0 115px;
    }

    .socials {
        border-bottom: 1px solid #4a4a4a;
    }

    .footer-brand {
        font-family: "Jost", sans-serif;
        font-weight: bold;
        font-size: 25px;
        text-decoration: none;
        color: white;
    }

    .footer-brand img {
        border-radius: 20%;
    }

    .icons-social a {
        text-decoration: none;
        color: white;
        padding: 0 5px;
    }

    /* <a href=""><i class="ri-instagram-line fs-5"></i></a><a href="">
    <i class="ri-facebook-circle-fill fs-5"></i></a><a href="">
    <i class="ri-twitter-fill fs-5"></i></a><a href="">
    <i class="ri-linkedin-box-fill fs-5"></i></a><a href="">
    <i class="ri-youtube-fill fs-5"></i></a>
     */

    .icons-social a:hover {
        transform: scale(1.2);
    }

    .instagram:hover {
        background: linear-gradient(45deg, #F58529, #DD2A7B, #8134AF, #515BD4);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }

    .facebook:hover {
        color: #3b5998;
    }

    .twitter:hover {
        color: #1DA1F2;
    }

    .linkedin:hover {
        color: #0077B5;
    }

    .youtube:hover {
        color: #FF0000;
    }


    .utils-link {
        border-bottom: 1px solid #4a4a4a;
        padding: 20px 0;
    }

    nav ul {
        list-style: none;
        padding: 0;
        display: flex;
    }

    nav li {
        margin: 0 10px;
        padding: 10px 20px 0 20px;
    }

    nav a {
        text-decoration: none;
        color: white;
        font-size: 15px;
    }

    nav a:hover {
        text-decoration: underline;
    }

    .arrow-up {
        padding: 5px 50px 0 0;
    }

    .arrow-up a {
        text-decoration: none;
        color: white;
    }

    #links {
        display: flex;
        justify-content: space-between;
        padding: 20px 0 20px 0;

    }

    .link1 ul,
    .link2 ul {
        list-style: none;
    }

    .link1,
    .link2 {
        text-align: left;
    }

    .link1 li,
    .link2 li {
        margin: 5px 0;
    }

    .link1 a,
    .link2 a {
        text-decoration: none;
        color: white;
    }

    .link1 a:hover,
    .link2 a:hover {
        text-decoration: underline;
    }


    .adress {
        display: flex;
        flex-direction: column;
        padding-right: 10px;
    }

    .adress a,
    p {
        text-decoration: none;
        color: white;
        padding-top: 10px;
    }

    .border-box {
        position: relative;
        padding: 10px;
        background: linear-gradient(#303030, #303030) padding-box,
            linear-gradient(to right, transparent, transparent, white) border-box;
        border-radius: 15px;
        border: 1px solid transparent;
    }

    .button-container {
        width: 420px;
        height: auto;
        background-color: #f0f0f0;
        border-radius: 10px;
        overflow: hidden;
        position: relative;
    }

    .background-image {
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
    }

    .launch-button {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: rgba(255, 255, 255, 0.7);
        padding: 5px 35px;
        text-align: center;
        display: inline-block;
        font-size: 16px;
        border-radius: 5px;
        border: none;
    }

    .launch-button a {
        text-decoration: none;
        color: black;
    }

    .Copyright {
        color: white;
        border-top: 1px solid #4a4a4a;
    }

    @media (min-width: 768px) and (max-width: 1023px) {

        #footer .container {
            padding: 20px 40px;
        }

        .socials {
            flex-direction: column;
            align-items: center;
            text-align: center;
        }

        #links {

            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
            text-align: center;
            padding: 20px 0;

            .link1,
            .link2,
            .adress {
                display: inline-block;
                vertical-align: top;
                margin-bottom: 20px;
                text-align: center;
            }

            .button-container {
                width: 100%;
                margin-top: 20px;
                display: flex;
                flex-direction: column;
                align-items: center;
                padding: 100px;
            }

            .background-image {
                width: 100%;
                height: auto;
                margin-bottom: 20px;
            }

            .launch-button {
                background-color: rgba(255, 255, 255, 0.7);
                padding: 10px 20px;
                text-align: center;
                font-size: 16px;
                border-radius: 5px;
                border: none;
                margin-top: 10px;
            }

            .launch-button a {
                text-decoration: none;
                color: black;
            }
        }
    }


    @media (max-width: 768px) {
        #footer .container {
            padding: 20px 40px;
        }

        .footer-brand {
            text-align: center;
            font-size: 20px;
            flex-wrap: nowrap;
        }

        .icons-social {
            text-align: center;
            flex-direction: row;
            flex-wrap: wrap;
            display: flex;
            justify-content: center;
            justify-content: space-around;
        }

        .utils-link {
            text-align: center;
            flex-direction: row;
            align-items: center;
            width: 100%;
            padding: 0 10px;
        }

        nav {
            justify-content: center;
        }

        nav ul {
            flex-direction: row;
            text-align: center;
            display: flex;
            justify-content: center;
            width: 100%;
        }

        .arrow-up {
            display: none;
        }

        #links {
            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
            text-align: center;
            padding: 20px 0;
        }

        .link1,
        .link2 {
            flex: 1 1 45%;
            margin-bottom: 10px;
            text-align: center;
        }

        .adress {
            width: 100%;
            text-align: center;
            margin-bottom: 20px;
        }

        .button-container {
            width: 100%;
            margin-top: 20px;
        }

        .button-container {
            width: 100%;
            margin-top: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 85px;
        }

        .background-image {
            width: 100%;
            height: auto;
            margin-bottom: 20px;
        }

        .launch-button {
            background-color: rgba(255, 255, 255, 0.7);
            padding: 10px 20px;
            text-align: center;
            font-size: 16px;
            border-radius: 5px;
            border: none;
            margin-top: 10px;
        }

        .launch-button a {
            text-decoration: none;
            color: black;
        }
    }

    #photofooter{
        background-position: center;
        background-image: url(file_assets/Photo.png);
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>