<section id="footer" class="text-center text-lg-starttext-muted">
    <!-- Section: Social media -->
    <div class="container">
        <section class="socials d-flex justify-content-center justify-content-lg-between p-4">
            <!-- Left -->
            <div class="me-5">
                <a class="footer-brand" href="#">
                    <img src="file_assets/LogoNex.png" alt="Logo" width="35" height="40" class="d-inline-block align-text-top">
                    NexumiaCRM
                </a>
            </div>
            <div class="icons-social">
                <a href=""><i class="ri-instagram-line fs-5"></i></a>
                <a href=""><i class="ri-facebook-circle-fill fs-5"></i></a>
                <a href=""><i class="ri-twitter-fill fs-5"></i></a>
                <a href=""><i class="ri-linkedin-box-fill fs-5"></i></a>
                <a href=""><i class="ri-youtube-fill fs-5"></i></a>
            </div>
        </section>
        <section class="utils-link d-flex justify-content-center justify-content-lg-between">
            <nav>
                <ul>
                    <li><a href="#">Liens Utiles</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Contacte</a></li>
                    <li><a href="#">Ce Lancer</a></li>
                </ul>
            </nav>
            <div class="arrow-up">
                <a href=""><i class="ri-arrow-up-s-line fs-3"></i></a>
            </div>
        </section>
        <section id="links">
            <div class="link1">
                <ul>
                    <li><a href="">Tyrolim</a></li>
                    <li><a href="">CGU</a></li>
                    <li><a href="">CGV</a></li>
                    <li><a href="">Legal</a></li>
                </ul>
            </div>
            <div class="link2">
                <ul>
                    <li><a href="">Solution</a></li>
                    <li><a href="">Produit</a></li>
                    <li><a href="">Devis</a></li>
                    <li><a href="">Se Connecter</a></li>
                </ul>
            </div>
            <div class="adress">
                <div class="adress1  border-box mb-1">
                    <p>252 Avenue Jean Jaurès<br>Décines-Charpieu, France</p>
                </div>
                <div class="adress2  border-box">
                    <p><a href="tel:+33611112669">+33 6 11 11 26 69<br>Officiel@Tyrolium.fr</a></p>
                </div>
            </div>
            <div class="button-container">
                <img src="file_assets/Photo.png" alt="Image de fond" class="background-image img-fluid">
                <button class="launch-button">Ce lancer</button>
            </div>
        </section>
        <div class="Copyright text-center p-4">
            Copyright © Tyrolium | Créer By Maxime Tournier
        </div>
    </div>
</section>
<style>
    #footer {
        background-color: #303030;
    }

    #footer .container {
        width: 100%;
        padding: 40px 115px 0 115px;
    }

    .socials {
        border-bottom: 1px solid #4a4a4a;
    }

    .footer-brand {
        font-family: "Jost", sans-serif;
        font-weight: bold;
        font-size: 25px;
        text-decoration: none;
        color: white;
    }

    .footer-brand img {
        border-radius: 20%;
    }

    .icons-social a {
        text-decoration: none;
        color: white;
        padding: 0 5px;
    }

    .utils-link {
        border-bottom: 1px solid #4a4a4a;
        padding: 20px 0;
    }

    nav ul {
        list-style: none;
        padding: 0;
        display: flex;
    }

    nav li {
        margin: 0 10px;
        padding: 10px 20px 0 20px;
    }

    nav a {
        text-decoration: none;
        color: white;
        font-size: 15px;
    }

    .arrow-up {
        padding: 5px 50px 0 0;
    }

    .arrow-up a {
        text-decoration: none;
        color: white;
    }

    #links {
        display: flex;
        justify-content: space-between;
        padding: 20px 0 20px 0;

    }

    .link1 ul,
    .link2 ul {
        list-style: none;
    }

    .link1,
    .link2 {
        text-align: left;
    }

    .link1 li,
    .link2 li {
        margin: 5px 0;
    }

    .link1 a,
    .link2 a {
        text-decoration: none;
        color: white;
    }

    .adress {
        display: flex;
        flex-direction: column;
    }

    .adress a,
    p {
        text-decoration: none;
        color: white;
    }

    .border-box {
        position: relative;
        padding: 5px;
        border-radius: 15px;
        overflow: hidden;
    }

    .border-box::after {
        content: '';
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        width: 50%;
        border-radius: 0 15px 15px 0;
        background: linear-gradient(to right, transparent, white);
    }

    .button-container {
        width: 40%;
        height: auto;
        background-color: #f0f0f0;
        border-radius: 10px;
        overflow: hidden;
        position: relative;
    }

    .background-image {
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
    }

    .launch-button {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: rgba(255, 255, 255, 0.7);
        color: black;
        padding: 5px 35px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        border-radius: 5px;
    }

    .Copyright {
        color: white;
        border-top: 1px solid #4a4a4a;
    }

    @media (min-width: 768px) and (max-width: 1023px) {
        #links {

            .link1 ul,
            .link2 ul {
                padding-right: 35px;
            }

            .link1,
            .link2 {
                text-align: center;
            }

            .button-container {
                width: 100%;
                margin-top: 20px;
            }
        }
    }


    @media (max-width: 768px) {
        #footer .container {
            padding: 15px;
        }

        .socials {
            padding: 20px;
        }

        .footer-brand {
            text-align: center;
            font-size: 20px;
            flex-wrap: nowrap;
        }

        .icons-social {
            text-align: center;
            flex-direction: row;
            flex-wrap: wrap;
            display: flex;
            justify-content: center;
            justify-content: space-around;
        }

        .utils-link {
            text-align: center;
            flex-direction: column;
            align-items: center;
            width: 100%;
            padding: 0 10px;
        }

        nav {
            justify-content: center;
        }

        nav ul {
            flex-direction: column;
            text-align: center;
        }

        .arrow-up {
            padding: 5px 0 0 0;
        }

        #links {
            flex-direction: column;
            align-items: center;
        }

        .link1 ul,
        .link2 ul {
            padding-right: 35px;
        }

        .link1,
        .link2 {
            text-align: center;
        }

        .button-container {
            width: 100%;
            margin-top: 20px;
        }
    }
</style>