<section id="leads-management">
    <div class="background-image">
        <img src="file_assets/Background-middle.png" alt="Background image" class="img-fluid bg-image">
    </div>
    <div class="container">
        <div class="image-content">
            <img src="file_assets/img-section-leads.png" alt="Analyse des ventes" class="img-fluid">
        </div>
        <div class="content">
            <div class="text-content">
                <h2>Attribuer Des Leads Et <br> Simplifier La Gestion Des Leads</h2>
                <p>Suite logicielle unique et puissante pour gérer l'ensemble de votre entreprise, présentée par une entreprise ayant une vision à long terme pour transformer votre façon de travailler.</p>
                <div class="features">
                    <div class="feature-item">
                        <span class="dot blue"></span>
                        <div>
                            <h3>Génération De Leads</h3>
                            <p>Le guide aide les entreprises à accroître la satisfaction des clients et des agents, réduisant également les coûts de support.</p>
                        </div>
                    </div>
                    <div class="feature-item">
                        <span class="dot blue"></span>
                        <div>
                            <h3>E-Mail De L'équipe</h3>
                            <p>Regroupez vos contacts par emplacement, âge et presque n'importe quel comportement grâce à des outils de segmentation avancés.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<style>
    #leads-management {

        position: relative;
        padding-bottom: 195px;
        padding-top: 50px;
        overflow: hidden;

        .background-image {
            position: absolute;
            top: 0;
            left: 0;
            width: 40%;
            height: 100%;
            z-index: 0;
        }

        .container {
            position: relative;
            z-index: 1;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .text-content {
            max-width: 95%;
            color: #333;
            padding: 0 10px 0 80px;
        }

        .text-content h2 {
            font-family: "Jost", sans-serif;
            font-style: SemiBold;
            color: #333;
            margin-bottom: 20px;
        }

        .text-content p {
            font-family: "Open Sans", sans-serif;
            color: #4e4e4e;
            margin-bottom: 30px;
            font-size: 15px;
        }

        .text-content h3 {
            font-family: "Jost", sans-serif;
            font-style: SemiBold;
            color: #333;
            font-size: 20px;
        }

        .features {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .feature-item {
            display: flex;
            align-items: flex-start;
            gap: 10px;
        }

        .dot {
            width: 30px;
            height: 17px;
            border-radius: 50%;
            margin-top: 6px;
        }

        .blue {
            background-color: #47CFFF;
        }

        .image-content {
            width: 110%;
        }

        @media (min-width: 768px) and (max-width: 1023px) {

            padding-bottom: 50px;

            .container {
                flex-direction: column;
                align-items: center;
                text-align: center;
            }

            .image-content {
                width: 80%;
            }
        }

        @media (max-width: 768px) {

            padding-bottom: 10px;

            .container {
                flex-direction: column;
                align-items: center;
                text-align: center;
            }

            .text-content,
            .image-content {
                max-width: 100%;
            }

            .image-content {
                width: 90%;
            }

            .text-content {
                padding: 0 40px;
                text-align: center;
            }

            .dot {
                width: 20px;
                height: 10px;
            }

            .background-image {
                position: absolute;
                top: 0;
                left: 0;
                width: 75%;
                height: 110%;
                z-index: 0;
            }
        }

    }
</style>