<section id="navbar">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="index.php">
                <img src="file_assets/LogoNex.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
                NexiumiaCRM
            </a>
            <div id="burger-menu">
                <span></span>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php#leads-management">Solution</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php#crm">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="formulaire.php?form=quote">Devis</a>
                    </li>
                    <li class="nav-item">
                        <button type="button">
                            <a class="nav-link" href="formulaire.php?form=login">Se connecter</a>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="menu">
        <ul>
            <li><a href="index.php#leads-management">Solution</a></li>
            <li><a href="index.php#crm">Products</a></li>
            <li><a href="formulaire.php?form=quote">Devis</a></li>
            <li class="nav-item">
                <button type="button" style="
        border-radius: 14px;">
                    <a style="margin-top: 15px;margin-bottom: 15px" class="nav-link" href="formulaire.php?form=login">Se connecter</a>
                </button>
            </li>
        </ul>
    </div>
</section>



<style>
    #navbar {
        .navbar {
            width: 100%;
            padding: 40px 115px 0 115px;
        }

        .navbar-brand {
            font-family: "Jost", sans-serif;
            font-weight: bold;
            font-size: 25px;
            /*text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);*/
        }

        .navbar-brand img {
            border-radius: 20%;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .navbar-brand:hover {
            text-decoration: none;
        }

        .nav-item {
            padding: 0 10px 0 10px;
        }

        .nav-item button {
            background-color: #303030;
            border-radius: 5%;
            padding: 1px 15px 1px 15px;
            border: none;
        }

        .nav-item button:hover {
            background-color: #606060;
        }

        .nav-item button:hover a {
            color: white;
            text-decoration: none;
        }

        .nav-item button a {
            color: white;
        }

        .nav-link:hover {
            color: black;
        }



        @media (max-width: 992px) {
            .navbar-toggler {
                margin-left: auto;
            }

            .container {
                padding-left: 15px;
                padding-right: 15px;
            }

            .navbar {
                padding: 15px 0;
            }
        }

    }

    #burger-menu {
        display:none;
        cursor: pointer;
        height: 27px;
        width: 27px;
        margin: 50px;
        overflow: visible;
        position: relative;
        z-index:2;
    }
    #burger-menu span,
    #burger-menu span:before,
    #burger-menu span:after {
        background: #000000;
        display: block;
        height: 4px;
        opacity: 1;
        position: absolute;
        transition: 0.3s ease-in-out;
    }
    #burger-menu span:before,
    #burger-menu span:after {
        content: "";
    }
    #burger-menu span {
        right: 0px;
        top: 13px;
        width: 27px;
    }
    #burger-menu span:before {
        right: 0px;
        top: -10px;
        width: 16px;
    }
    #burger-menu span:after {
        right: 0px;
        top: 10px;
        width: 20px;
    }

    #burger-menu.close span {
        transform: rotate(-45deg);
        top: 13px;
        width: 27px;
    }
    #burger-menu.close span:before {
        top: 0px;
        transform: rotate(90deg);
        width: 27px;
    }
    #burger-menu.close span:after {
        top: 0px;
        left:0;
        transform: rotate(90deg);
        opacity:0;
        width:0;
    }



    #menu{
        z-index:1;
        min-width:100%;
        min-height:100%;
        position: fixed;
        top:0;
        height:0;
        visibility: hidden;
        opacity: 0;
        text-align:center;
        padding-top:20px;
        transition: all 0.3s ease-in-out;

    }

    #menu.overlay{
        visibility: visible;
        opacity: 1;
        padding-top:100px;
        background: rgb(255, 255, 255);
    }

    #menu li{
        list-style:none;
    }
    #menu a{
        color: #000000;
        display:block;
        font-size: 32px;
        margin-bottom:30px;
        text-decoration:none;
    }

    @media (max-width: 991px){
        #burger-menu{display: block}
    }
</style>
<script>
    var burgerMenu = document.getElementById('burger-menu');
    var overlay = document.getElementById('menu');
    burgerMenu.addEventListener('click',function(){
        this.classList.toggle("close");
        overlay.classList.toggle("overlay");
    });

</script>