<nav class="navbar navbar-expand-lg">
  <div class="container-fluid mx-5">
    <img class="" src="./assets/nexlogo.png" alt="">
    <a class="navbar-brand" href="./index.php">NexiumiaCRM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end mx-4" id="navbarNavAltMarkup">
      <div class="navbar-nav gap-4">
        <a class="nav-link" href="#">Solution</a>
        <a class="nav-link " href="#">Products</a>
        <a class="nav-link" href="#">Devis</a>
        <a class="nav-link rectangle" href="./login.php">Se connecter</a>
      </div>
    </div>
  </div>
</nav>